# Form implementation generated from reading ui file '..\blackbox-fetch\blackbox_fetch\ui\main_window\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 200)
        MainWindow.setMinimumSize(QtCore.QSize(250, 200))
        MainWindow.setMaximumSize(QtCore.QSize(250, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setScaledContents(False)
        self.status_label.setWordWrap(True)
        self.status_label.setObjectName("status_label")
        self.horizontalLayout.addWidget(self.status_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.output_folder_button = QtWidgets.QPushButton(self.centralwidget)
        self.output_folder_button.setObjectName("output_folder_button")
        self.horizontalLayout_2.addWidget(self.output_folder_button)
        self.output_folder_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.output_folder_edit.setInputMask("")
        self.output_folder_edit.setFrame(False)
        self.output_folder_edit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_folder_edit.setReadOnly(True)
        self.output_folder_edit.setObjectName("output_folder_edit")
        self.horizontalLayout_2.addWidget(self.output_folder_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.log_bar = QtWidgets.QStatusBar(MainWindow)
        self.log_bar.setSizeGripEnabled(False)
        self.log_bar.setObjectName("log_bar")
        MainWindow.setStatusBar(self.log_bar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Blackbox fetch"))
        self.status_label.setText(_translate("MainWindow", "status"))
        self.output_folder_button.setText(_translate("MainWindow", "Change"))
        self.output_folder_edit.setPlaceholderText(_translate("MainWindow", "select output folder"))
