name: ci
on:
  - push

jobs:
  build_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        with:
          path: |
            .venv
            .cache
            env
          key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
            ${{ runner.os }}-
      - name: Install dependencies
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: "true"
          POETRY_CACHE_DIR: .cache
        run: |
          python -m venv env
          ./env/Scripts/pip install --cache-dir .cache poetry
          ./env/Scripts/poetry config --list
          ./env/Scripts/poetry install
      - name: Build .exe
        run: ./env/Scripts/poetry run pyinstaller -w -y --clean --log-level WARN ./blackbox_fetch/main.py -F --name blackbox-fetch
      - uses: actions/upload-artifact@v2
        # Upload only on specific branches
        if: endsWith(github.ref, 'master') || endsWith(github.ref, 'dev')
        with:
          name: blackbox_fetch_exe
          path: dist/blackbox-fetch.exe

  release:
    needs: build_win
    runs-on: windows-latest
    if: endsWith(github.ref, 'master') || endsWith(github.ref, 'dev')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        with:
          path: |
            .venv
            .cache
            env
          key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
            ${{ runner.os }}-

      - uses: actions/download-artifact@v2
        with:
          name: blackbox_fetch_exe

      - name: Download git-chglog
        run: |
          Invoke-WebRequest -Uri "https://github.com/git-chglog/git-chglog/releases/download/v0.15.0/git-chglog_0.15.0_windows_amd64.zip" -OutFile "git-chglog.zip"
          Expand-Archive -Path git-chglog.zip

      - name: Bump version for master or dev branch
        id: version
        run: |
          $branch = git rev-parse --abbrev-ref HEAD

          if ($branch -eq "dev"){
            echo Bumping patch version
            ./env/Scripts/poetry version patch
          }

          if ($branch -eq "master") {
            echo Bumping minor version
            ./env/Scripts/poetry version minor
          }

          $version = ./env/Scripts/poetry version -s
          $tag = "v$version"

          git config --global user.name 'Github Action'
          git config --global user.email 'github-action@users.noreply.github.com'
          git commit -am "Auto bump version to $version"
          git tag $tag

          git-chglog/git-chglog.exe -c .github/config.yml --output CHANGELOG.md ..$tag

          echo "::set-output name=version::$version"
          echo "::set-output name=tag::$tag"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          tags: true
          branch: ${{ github.ref }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          prerelease: true
          files: blackbox-fetch.exe
          name: "blackbox-fetch ${{ steps.version.outputs.version }}"
          tag_name: "${{ steps.version.outputs.tag }}"
          fail_on_unmatched_files: true
