
name: Autorelease
on:
  - workflow_dispatch


jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sashgorokhov/blackbox-fetch/.github/workflows/build.yml